spring:
  redis:
    host: 150.28.79.190 # Redis server host.
    port: 6379 # Redis server port.
    password: redis-twd # Login password of the redis server.
    database: 0 # Database index used by the connection factory.    