server:
  port: 9010
  
logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
 
#spring
#  datasource
#    driverClassName=org.h2.Driver
#    url=jdbc:h2:~/db1;DB_CLOSE_ON_EXIT=FALSE
 
spring:
  h2:
    console:
      enabled: true
      path: /h2console