spring:
  batch:
    job:
      enabled: false
  datasource:
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 50
      minimum-idle: 20

logging:
  level:
    io.github.joyoungc.batch: DEBUG

batch:
  target-url: http://localhost:9000
  core-task-pool-size: 50
  max-task-pool-size: 100
  chunk-size: 100
  
rest:
  trans-type: async
  read-timeout: 3000
  connect-timeout: 3000 