/* 관리자 마스터 테이블 */
CREATE TABLE ADM_USER (
	ADM_ID int not null,
	USER_ID varchar(50) not null,
	USER_NM varchar(50) not null,
	PASSWORD varchar(100) not null,
	EMALE varchar(50),
	PWD_AUTH_DT date,
	ENABLED number(1) not null DEFAULT 1
);

ALTER TABLE ADM_USER ADD CONSTRAINT PK_ADM_USER PRIMARY KEY (ADM_ID);
ALTER TABLE ADM_USER ADD CONSTRAINT UK_ADM_USER_01 UNIQUE (USER_ID);


/* 관리자 권한 테이블 */
CREATE TABLE ADM_ROLE (
	ROLE_ID int not null,
	ROLE_NM varchar(20) not null
);

ALTER TABLE ADM_ROLE ADD CONSTRAINT PK_ADM_ROLE PRIMARY KEY (ROLE_ID);
ALTER TABLE ADM_ROLE ADD CONSTRAINT UK_ADM_ROLE_01 UNIQUE (ROLE_NM);


/* 관리자 권한 매핑 테이블 */
CREATE TABLE ADM_USER_ROLES (
	ADM_ID int not null,
	ROLE_ID int not null
);

ALTER TABLE ADM_USER_ROLES ADD CONSTRAINT PK_ADM_USER_ROLES PRIMARY KEY (ADM_ID,ROLE_ID);