logging:
  level:
    root: INFO
    io.github.joyoungc: DEBUG
    org.springframework:
      web: DEBUG
      boot.autoconfigure.logging: DEBUG
    
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
          
server:
  port: 9000 
  
  