server:
  port: 9000

logging:
  level:
    root: INFO
    io.github.joyoungc: DEBUG
    org.springframework:
      web: DEBUG
      boot.autoconfigure.logging: INFO

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  devtools:
    livereload:
      enabled: true