server:
  port: 9090

spring:
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
  output:
    ansi:
      enabled: always
  # JPA 공통 설정
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true

  jackson:
    default-property-inclusion: always

  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false



logging:
  level.org.hibernate:
    #    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
