spring:
  datasource.schema: classpath:import.sql
  
mybatis:
    type-aliases-package: io.github.joyoungc.common.model;
    mapper-locations: classpath:mybatis/**/*-mapper.xml
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30  

# mybatis:
#   config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    io.github.joyoungc.mybatis: TRACE
    org.springframework.jdbc: DEBUG

server:
  port: 9000 