server:
  port: 9000
  
spring:
  datasource.schema: classpath:import.sql
  
mybatis:
  type-aliases-package: io.github.joyoungc.common.model;
  mapper-locations: classpath:mybatis/**/*-mapper.xml
  configuration:
    lazy-loading-enabled: false  # 지연로딩 사용여부
    default-fetch-size: 100
    default-statement-timeout: 10  # DB 응답 타임아웃 설정
    map-underscore-to-camel-case: true  # DB 컬럼명을 JAVA의 Camel표기법으로 자동 매핑 설정
    jdbc-type-for-null: NULL  # mybatis로 넘어오는 parameter가 null인 경우, jdbcType을 Setting
    call-setters-on-nulls: true  # 가져온 값이 null일때 setter나 맵의 put 메소드를 호출할지를 명시 (false일경우, null인 field는 제거되어 나타남 : default는 false

# mybatis:
#   config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    io.github.joyoungc.mybatis: TRACE
    org.springframework.jdbc: DEBUG